version: '3.5'

networks:
  proxynet:
    external: true

services:
  traefik:
    image: traefik:3.0
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxynet
    ports:
      - 380:80
      - 3443:443
    environment:
      - CF_ZONE_API_TOKEN=${CF_API_TOKEN}
      # - CF_DNS_API_TOKEN=${CF_API_TOKEN}
      # If you choose to use an API Key instead of a Token, specify your email as well
      # - CF_API_EMAIL=${CF_EMAIL}
      # - CF_API_KEY=${CF_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APPDATA_PATH}/traefik.yml:/traefik.yml:ro
      - ${APPDATA_PATH}/acme.json:/acme.json
      - ${APPDATA_PATH}/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`proxy-dash.mcmurray.tech`)"
      # - "traefik.http.middlewares.traefik-auth.basicauth.users=${DASHBOARD_USER}:${DASHBOARD_PWD}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.dashboard-router.entrypoints=https"
      - "traefik.http.routers.dashboard-router.rule=Host(`proxy-dash.mcmurray.tech`)"
      # - "traefik.http.routers.dashboard-router.middlewares=traefik-auth"
      - "traefik.http.routers.dashboard-router.tls=true"
      - "traefik.http.routers.dashboard-router.tls.certresolver=cloudflare"
      - "traefik.http.routers.dashboard-router.tls.domains[0].main=mcmurray.tech"
      - "traefik.http.routers.dashboard-router.tls.domains[0].sans=*.mcmurray.tech"
      - "traefik.http.routers.dashboard-router.service=api@internal"