version: '3.5'

# Build for NC image:
# orginal cmd: sh -c "chown -R :www-data /data && chmod -R g+rwx /data && chmod -R 0770 /data"
# LABEL version="${NC_VERSION}"
# FROM nextcloud:${NC_VERSION}
# ENTRYPOINT chown -R :www-data /data && chmod -R g+rwx /data && chmod -R 0770 /data && /bin/bash

# Build for ES image:
# Name: local/elasticsearch:${ES_VERSION}
# FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
# RUN bin/elasticsearch-plugin install --batch ingest-attachment

networks:
  backend:
    internal: true
  proxynet:
    external: true

services:
  onlyoffice:
    image: onlyoffice/documentserver:7.5.1
    container_name: nextcloud-onlyoffice
    stdin_open: true
    volumes:
      - ${APPDATA_PATH}/oo_data:/var/www/onlyoffice/Data
      - ${APPDATA_PATH}/oo_log:/var/log/onlyoffice
      - ${APPDATA_PATH}/oo_fonts:/usr/share/fonts
    networks:
      - proxynet
    environment:
      - JMT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: mariadb:10
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ${APPDATA_PATH}/db:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:7.2
    container_name: nextcloud-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${APPDATA_PATH}/cache:/data
    networks:
      - backend
  
  app:
    image: nextcloud:27
    container_name: nextcloud
    depends_on:
      - db
      - redis
    volumes:
      - ${APPDATA_PATH}/app:/var/www/html
      - /mnt/user/NextCloud:/data
    networks:
      - backend
      - proxynet
    environment:
      - PUID=99
      - PGID=100
      - PHP_MEMORY_LIMIT=8192M
      - PHP_UPLOAD_LIMIT=32G
      - NEXTCLOUD_DATA_DIR=/data
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.php-cron.schedule: "@every 5m"
      ofelia.job-exec.php-cron.user: "www-data"
      ofelia.job-exec.php-cron.command: "php -f /var/www/html/cron.php"
      ofelia.job-exec.occ-scan.schedule: "@every 5m"
      ofelia.job-exec.occ-scan.user: "www-data"
      ofelia.job-exec.occ-scan.command: "php occ files:scan --all --unscanned --generate-metadata"
      ofelia.job-exec.occ-scan-appdata.schedule: "@weekly"
      ofelia.job-exec.occ-scan-appdata.user: "www-data"
      ofelia.job-exec.occ-scan-appdata.command: "php occ files:scan-app-data"
      ofelia.job-exec.occ-cleanup.schedule: "@hourly"
      ofelia.job-exec.occ-cleanup.user: "www-data"
      ofelia.job-exec.occ-cleanup.command: "php occ files:cleanup"
      ofelia.job-exec.occ-db-indices.schedule: "@weekly"
      ofelia.job-exec.occ-db-indices.user: "www-data"
      ofelia.job-exec.occ-db-indices.command: "php occ db:add-missing-indices"
      ofelia.job-exec.occ-index.schedule: "@hourly"
      ofelia.job-exec.occ-index.user: "www-data"
      ofelia.job-exec.occ-index.command: "php occ fulltextsearch:index"
      ofelia.job-exec.data-chown.schedule: "@hourly"
      ofelia.job-exec.data-chmod1.schedule: "@hourly"
      ofelia.job-exec.data-chmod2.schedule: "@hourly"
      ofelia.job-exec.data-chown.user: "root"
      ofelia.job-exec.data-chmod1.user: "root"
      ofelia.job-exec.data-chmod2.user: "root"
      ofelia.job-exec.data-chown.command: "chown -R :www-data /data"
      ofelia.job-exec.data-chmod1.command: "chmod -R g+rwx /data"
      ofelia.job-exec.data-chmod2.command: "chmod -R 0770 /data"
      # Requires Preview Generator https://apps.nextcloud.com/apps/previewgenerator
      # ofelia.job-exec.occ-preview.schedule: "@every 15m"
      # ofelia.job-exec.occ-preview.user: "www-data"
      # ofelia.job-exec.occ-preview.command: "php occ preview:pre-generate"

  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    container_name: nextcloud-elasticsearch
    pull_policy: build
    build:
      context: .
      dockerfile: elasticsearch.Dockerfile
      args:
        - VERSION=${ES_VERSION}
      tags:
        - "elasticsearch:${ES_VERSION}"
    volumes:
      - ${APPDATA_PATH}/es_data:/usr/share/elasticsearch/data
    networks:
      - backend
    environment:
      - PUID=99
      - PGID=100
      - ELASTIC_PASSWORD=${ES_PWD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: nextcloud-cron
    depends_on:
      - app
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
