version: '3.5'

# Build for NC image:
# orginal cmd: sh -c "chown -R :www-data /data && chmod -R g+rwx /data && chmod -R 0770 /data"
# LABEL version="${NC_VERSION}"
# FROM nextcloud:${NC_VERSION}
# ENTRYPOINT chown -R :www-data /data && chmod -R g+rwx /data && chmod -R 0770 /data && /bin/bash

# Build for ES image:
# Name: local/elasticsearch:${ES_VERSION}
# FROM docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
# RUN bin/elasticsearch-plugin install --batch ingest-attachment

networks:
  backend:
    internal: true
  proxynet:
    external: true

services:
  onlyoffice:
    image: onlyoffice/documentserver:${OO_VERSION}
    container_name: nextcloud-onlyoffice
    stdin_open: true
    volumes:
      - ${APPDATA_PATH}/oo_data:/var/www/onlyoffice/Data
      - ${APPDATA_PATH}/oo_log:/var/log/onlyoffice
      - ${APPDATA_PATH}/oo_fonts:/usr/share/fonts
    networks:
      - proxynet
    environment:
      - JMT_ENABLED=true
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: mariadb:${MDB_VERSION}
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - ${APPDATA_PATH}/db:/var/lib/mysql
    networks:
      - backend
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:${R_VERSION}
    container_name: nextcloud-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ${APPDATA_PATH}/cache:/data
    networks:
      - backend
  
  app:
    image: nextcloud:${NC_VERSION}
    container_name: nextcloud
    depends_on:
      - db
      - redis
    volumes:
      - ${APPDATA_PATH}/app:/var/www/html
      - /mnt/user/NextCloud:/data
    networks:
      - backend
      - proxynet
    environment:
      - PUID=99
      - PGID=100
      - PHP_MEMORY_LIMIT=8192M
      - PHP_UPLOAD_LIMIT=32G
      - NEXTCLOUD_DATA_DIR=/data
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=${DB_PWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  elasticsearch:
    image: elasticsearch:${ES_VERSION}
    container_name: nextcloud-elasticsearch
    pull_policy: build
    build:
      context: .
      dockerfile: elasticsearch.Dockerfile
      args:
        - VERSION=${ES_VERSION}
      tags:
        - "elasticsearch:${ES_VERSION}"
    volumes:
      - ${APPDATA_PATH}/es_data:/usr/share/elasticsearch/data
    networks:
      - backend
    environment:
      - PUID=99
      - PGID=100
      - ELASTIC_PASSWORD=${ES_PWD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node

  helper:
    image: alpine:${A_VERSION}
    container_name: nextcloud-helper
    pull_policy: build
    build:
      context: .
      dockerfile: helper.Dockerfile
      args:
        - VERSION=${A_VERSION}
      tags:
        - "alpine:${A_VERSION}"
    privileged: true
    depends_on:
      - app
      - elasticsearch
      - onlyoffice
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        external: true
        name: none
