networks:
  proxynet:
    external: true

services:
  external-proxy:
    image: jc21/nginx-proxy-manager:${NPM_VERSION}
    container_name: external-proxy
    environment:
      - TZ=America/Los_Angeles
      - DB_SQLITE_FILE=/data/database.sqlite
      - PUID=99
      - PGID=100
    networks:
      - proxynet
    ports:
      - "1081:81"
      - "1080:80"
      - "10443:443"
      - "3000:3000"
    volumes:
      - ${APPDATA_PATH}/data:/data
      - ${APPDATA_PATH}/letsencrypt:/etc/letsencrypt
      - ${TMP_PATH}/var/log:/var/log
    labels:
      net.unraid.docker.webui: http://${UI_URL}
      net.unraid.docker.icon: https://nginxproxymanager.com/icon.png