networks:
  br0:
    external: true

services:
  internal-proxy:
    image: jc21/nginx-proxy-manager:${NPM_VERSION}
    container_name: internal-proxy
    environment:
      - TZ=America/Los_Angeles
    networks:
      br0:
        ipv4_address: ${LAN_IP}
    volumes:
      - ${APPDATA_PATH}/data:/data
      - ${APPDATA_PATH}/letsencrypt:/etc/letsencrypt
      - ${TMP_PATH}/var/log:/var/log
    labels:
      net.unraid.docker.webui: http://${UI_URL}
      net.unraid.docker.icon: https://nginxproxymanager.com/icon.png