networks:
  bridge:
    external: true

services:
  android-emulator:
    image: budtmo/docker-android:emulator_14.0
    container_name: android-emulator
    privileged: true
    volumes:
      - ${APPDATA_PATH}/data:/home/androidusr
    networks:
      - bridge
    ports:
      - "5900:5900"
    environment:
      EMULATOR_DEVICEL: Samsung Galaxy S10
    devices:
      - /dev/kvm
    labels:
      net.unraid.docker.webui: http://10.0.0.10:5900
      net.unraid.docker.icon: https://raw.githubusercontent.com/tiagorlampert/RootChecker/master/res/Logo.png