version: '3.5'

networks:
  backend:
    internal: true
  proxynet:
    external: true

services:
  db:
    image: mariadb:${MDB_VERSION}
    container_name: mcmurray-tech-db
    volumes:
      - ${APPDATA_PATH}/db_data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DB_PWD}
    labels:
      net.unraid.docker.icon: https://mariadb.com/wp-content/uploads/2019/11/mariadb-logo-vert_blue-transparent.png

  wordpress:
    image: wordpress:${WP_VERSION}
    container_name: mcmurray-tech-wordpress
    volumes:
      - ${APPDATA_PATH}/wp_data:/var/www/html
    networks:
      - backend
      - proxynet
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${DB_PWD}
    labels:
      net.unraid.docker.webui: https://${UI_URL}
      net.unraid.docker.icon: https://banner2.cleanpng.com/20180504/ocw/avdmwp8cv.webp