networks:
  br0:
    external: true
  proxynet:
    external: true

services:
  npm:
    image: jc21/nginx-proxy-manager:${NPM_VERSION}
    container_name: NPM
    environment:
      - TZ=America/Los_Angeles
      - DB_SQLITE_FILE=/data/database.sqlite
      - PUID=99
      - PGID=100
    networks:
      br0:
        ipv4_address: ${LAN_IP}
      proxynet:
    volumes:
      - ${APPDATA_PATH}/data:/data
      - ${APPDATA_PATH}/letsencrypt:/etc/letsencrypt
      - ${TMP_PATH}/var/log:/var/log